#!/bin/bash
echo '#!/bin/bash' >> 0-alias
chmod u+x 0-alias
echo '#!/bin/bash' >> 1-hello_you
chmod u+x 1-hello_you
echo '#!/bin/bash' >> 2-path
chmod u+x 2-path
echo '#!/bin/bash' >> 3-paths
chmod u+x 3-paths
echo '#!/bin/bash' >> 4-global_variables
chmod u+x 4-global_variables
echo '#!/bin/bash' >> 5-local_variables
chmod u+x 5-local_variables
echo '#!/bin/bash' >> 6-create_local_variable
chmod u+x 6-create_local_variable
echo '#!/bin/bash' >> 7-create_global_variable
chmod u+x 7-create_global_variable
echo '#!/bin/bash' >> 8-true_knowledge
chmod u+x 8-true_knowledge
echo '#!/bin/bash' >> 9-divide_and_rule
chmod u+x 9-divide_and_rule
echo '#!/bin/bash' >> 10-love_exponent_breath
chmod u+x 10-love_exponent_breath
echo '#!/bin/bash' >> 11-binary_to_decimal
chmod u+x 11-binary_to_decimal
echo '#!/bin/bash' >> 12-combinations
chmod u+x 12-combinations
echo '#!/bin/bash' >> 13-print_float
chmod u+x 13-print_float
echo '#!/bin/bash' >> 14-decimal_to_hexadecimal
chmod u+x 14-decimal_to_hexadecimal
