#!/usr/bin/env bash
# This bash script transfers a file to a web server.
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -v -o StrictHostKeyChecking=no UserKnownHostsFile=/dev/null
fi
