#!/usr/bin/env bash
# This bash script installs Nginx onto a web server.
apt update
apt -y install nginx
ufw allow 'Nginx Full'
echo 'Holberton School for the win!' |
tee -a /var/www/html/index.nginx-debian.html
service nginx start
