#!/usr/bin/env bash
# This bash script redirects client to 301.
apt update
apt -y install nginx
ufw allow 'Nginx Full'
echo 'Holberton School for the win!' | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
var="\trewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "35i\$var" /etc/nginx/sites-enabled/default
