#!/usr/bin/env bash
# This bash script redirects client to 301.
sudo apt-get update
sudo apt-get -y install nginx
echo 'Holberton School for the win!' | sudo tee /var/www/html/index.nginx-debian.html
var="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "35i$var" /etc/nginx/sites-available/default
service nginx start
