#!/usr/bin/env bash
# This bash script redirects client to 404.

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Static Homepage
sudo echo 'Holberton School for the win!' | sudo tee /var/www/html/index.nginx-debian.html

# Redirect 301
var="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "35i$var" /etc/nginx/sites-available/default

# Custom 404
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
var2="error_page 404 /custom_404.html;\nlocation /custom_404.html {\nroot /var/www/html;\ninternal;\n}"
sudo sed -i "36i$var2" /etc/nginx/sites-available/default

# Start Nginx
sudo service nginx start
