#!/usr/bin/env bash
# shellcheck disable=SC2154
# This bash script configure web-02 to be identical to web-01
sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx Full'
var="add_header X-Served-By: $HOSTNAME"
sudo sed -i "45i$var" /etc/nginx/sites-available/default
sudo service nginx start
shellcheck -e SC2154 ~/0-custom_http_response-header
