#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Start Nginx
sudo service nginx start

# Install HAproxy
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy

# Config to manage via init script
sudo echo "ENABLED=1" >> /etc/default/haproxy

# Config with two web servers
var5="frontend localnodes\n\tbind 54.90.111.241:80\n\tdefault_backend nodes\n\nbackend nodes\n\tbalance roundrobin\n\tserver 1039-web-01 104.196.171.186:80 check\n\tserver 1039-web-02 34.204.40.84:80 check"
sudo echo $var5 >> /etc/haproxy/haproxy.cfg

# Start HAproxy
sudo service haproxy start
