#!/usr/bin/env bash
# This bash script has Nginx listening on port 80
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/" etc/nginx/sites-enabled/default
sudo sed -i "s/listen [::]:8080 default_server ipv6only=on;/listen localhost/" /etc/nginx/sites-enabled/default
sudo service nginx restart
