#!/usr/bin/env bash
# This script is displaying the visitor IP and HTTP status code in order based on the number of requests made by an IP from a Apache log file.
awk '{print $1 " " $9}' apache-access.log | sort -n | uniq -c | sort -rn
