#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but "Hi" for the 9th iteration
i=0
while [ $i -lt 9 ]
do
	echo "Holberton School"
	(( i++ ))
	if [ $i -eq 8 ]
	then
		echo "Hi"
		continue
	fi
done
