#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but with "bad luck" and "good luck" replacements
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo $minute
		(( minute++ ))
	done
	(( hour++ ))
done
