#!/usr/bin/env bash
#Creating Bash script to config an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2s//8.8.8.8	facebook.com\n/' ~/hosts.new
cat ~/hosts.new > /etc/hosts
