#!/usr/bin/env bash
# This bash script runs Nginx as user, nginx.

# Nginx must be listening on all active IPs on port 8080
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default

# Changing permissions of Nginx config file
sudo cd /etc/nginx/
sudo chmod 777 nginx.conf

# Access Nginx as nginx
sudo -u nginx nginx
sudo nginx
