#!/usr/bin/env bash
# This bash script runs Nginx as user, nginx.
pkill -f apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo chown -R nginx /etc/nginx
sudo chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
